### ISSUE TITLE
testing move to esm

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db-io#33]
This seems like a good package to test moving to esm in addition to a couple tools.

- [x] convert package to module
- [x] install and set up [ipjs](https://github.com/mikeal/ipjs)
- [x] convert tests to esm; run tests as esm or cjs with ipjs
- [x] install and set up [typedoc](https://typedoc.org/)
- [x] generate api documentation with typedoc

changes visible on [esm](https://github.com/orbitdb/orbit-db-io/tree/esm) branch

**Comment by aphelionz** [comment]
Looks good @tabcat, looking forward to seeing the results

**Comment by tabcat** [comment]
Everything works well but I don't like any of the doc generators I tried. the typedoc markdown plugin looked the best but still not great. Documenting interfaces with JSDoc is still useful as it improves readability and can be used to support typescript in the future.

Very happy with all the rest. Might clean this up a bit but don't plan on using these changes atm.
